# Generated by Django 4.2.7 on 2024-12-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
    ]
