# Generated by Django 4.2.7 on 2024-12-22 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0010_onetoonemeeting"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentoringSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("join_link", models.URLField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("rating", models.PositiveIntegerField(blank=True, null=True)),
                ("goals", models.TextField(blank=True, null=True)),
                ("resources", models.JSONField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentored_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mentoring Sessions",
                "ordering": ["date", "time"],
            },
        ),
        migrations.DeleteModel(
            name="OneToOneMeeting",
        ),
    ]
