# Generated by Django 4.2.7 on 2025-02-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mentoringsession_delete_onetoonemeeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='repy',
            new_name='reply',
        ),
    ]
