# Generated by Django 4.2.7 on 2025-02-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_book_bookpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
