# Generated by Django 4.2.7 on 2025-02-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_book_bookpurchase'),
        ('api', '0013_course_active'),
    ]

    operations = [
    ]
