# Generated by Django 4.2.7 on 2025-02-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_course_active'),
        ('api', '0013_teacher_expertise'),
    ]

    operations = [
    ]
