# Generated by Django 4.2.7 on 2025-02-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_learningmodule_alter_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmodule',
            name='created_at',
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
