# Generated by Django 4.2.7 on 2025-02-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
