# Generated by Django 4.2.7 on 2025-02-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_book_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_pages',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(null=True),
        ),
    ]
