# Generated by Django 4.2.7 on 2025-02-11 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_cart_book_bookcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(choices=[('course', 'Course'), ('book', 'Book')], default='course', max_length=10),
        ),
        migrations.DeleteModel(
            name='BookCart',
        ),
    ]
