# Generated by Django 4.2.7 on 2025-02-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_learningmodule_created_at_and_more'),
        ('api', '0026_remove_cart_book_remove_cart_type_alter_cart_course'),
    ]

    operations = [
    ]
