# Generated by Django 4.2.7 on 2025-03-28 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_remove_cart_book_remove_cart_type_alter_cart_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentoringsession',
            options={},
        ),
        migrations.RenameField(
            model_name='mentoringsession',
            old_name='join_link',
            new_name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='title',
        ),
        migrations.AlterField(
            model_name='mentoringsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='mentoringsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
