# Generated by Django 4.2.7 on 2025-04-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0027_alter_mentoringsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentoringsession',
            options={'ordering': ['date', 'time'], 'verbose_name_plural': 'Mentoring Sessions'},
        ),
        migrations.RenameField(
            model_name='mentoringsession',
            old_name='meeting_link',
            new_name='join_link',
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='resources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentoringsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentoringsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
