# Generated by Django 4.2.7 on 2025-04-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20250211_1216'),
        ('api', '0028_alter_mentoringsession_options_and_more'),
    ]

    operations = [
    ]
